version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: luizalabs_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
      - ./database/init-test.sql:/docker-entrypoint-initdb.d/init-test.sql

volumes:
  postgres_data_test: