version: '3.8'

services:
  luizalabs-ruby:
    image: luizalabs-ruby:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9292:9292"
    environment:
      DATABASE_PROD_URL:

volumes:
  postgres_data:
