name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: [5432:5432]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: luizalabs_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_TEST_URL: postgres://postgres:123456@localhost:5432/luizalabs_test
      PROFILE: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true 

      - name: Run tests
        run: bundle exec rspec


  # Desativado devido a descontinuação dos benefícios do plano gratuito da conta Azure.
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'luizalabs-ruby'
  #         slot-name: 'production'
  #         publish-profile: ${{ secrets.AZURE_PROFILE }}
  #         images: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/luizalabs-ruby:${{ github.sha }}'
