name: Continuous Integration

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:  
      DATABASE_URL: postgres://postgres:123456@localhost/luizalabs_test
      PROFILE: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: bundle install

      - name: Start test database
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Run tests
        run: bundle exec rspec